### PR TITLE
Added desktop shortcut & launch app after install feature. Along with klaw asar fix.

### PR DESCRIPTION
**Pull request by markmorris**
Feel free to criticise my code. Sorry for the repost i noticed the Shortcut was a hardcoded test value.

### CODE REVIEW

**Comment by markmorris** [comment]
I'm closing this pull request as im assuming this project is dead.

**Comment by schontz** [comment]
@bitdisaster is the project dead? It looks like there is some activity. If there are PR's that do not break code coverage will they be rolled in?

**Comment by markmorris** [comment]
@sst2010 Wow it's been so long, but I've been using my code changes for the past 2 years without problems, the only thing I can think of that would cause the error is you needed to add extensions: ['WixUtilExtension'] to the options. I might get the source back out and take a look.

**Comment by sst2010** [comment]
@markmorris I'm not very well versed with Wix. Even though I had to make a few changes to get it working for me, your solution helped a lot.

The updates were tested across several Windows devices and worked like a charm. So, I posted it if someone faces the same problem. That's all !!

If you need any help with debugging, let me know. Thanks again for your code !!

**Pull request closed without merging**
